### ISSUE TITLE
active or not 

### ISSUE THREAD

**Issue by ansarikhurshid786** [EddyVerbruggen/cordova-plugin-mapbox#95]
I am planning to use this plugin with ionic 3. 

I have created test app with ionic 3.  It is working like native app but in this plugin have few methods. 

can anyone help me how to use basic methods of mapbox with this plugin?

**Comment by ansarikhurshid786** [comment]
got to user's current location

**Comment by risinghero** [comment]
@ansarikhurshid786 you dont't need this plugin to get user's location.  Just use [cordova-plugin-geolocation](https://github.com/apache/cordova-plugin-geolocation)  to get position and then center map on it. You can also add marker if you would like to.

**Comment by ansarikhurshid786** [comment]
yes right but using geolocation plugin taking too much time.

**Comment by ansarikhurshid786** [comment]
How to change style of map?

**Comment by risinghero** [comment]
@ansarikhurshid786  why is it taking too much time?
@ansarikhurshid786  please, write in one thread. And if you asked question in one thread-don't open new question. I'm getting frustrated in what thread to answer your question

**Comment by risinghero** [comment]
@ansarikhurshid786  you can make style in mapbox and then point this plugin to your style
`show: (options: {
            /** your style url*/
            style: string,`

**Comment by ansarikhurshid786** [comment]
m sorry for frustration.

**Comment by ansarikhurshid786** [comment]
thanks a lot for your quick answer.
